### ISSUE TITLE
Request for Data Collection Code from VirtualHome

### ISSUE THREAD

**Issue by minghchen** [szxiangjn/world-model-for-language-model#2]
Hi Jiannan,

I am interested in your excellent work and would like to collect the data similarly. In order to proceed, could you kindly share the code you used for data collection from VirtualHome? Having access to this would greatly facilitate my research and enable me to follow your methodology more accurately.

I appreciate your time and consideration, and I look forward to your positive response.

Thank you in advance!

**Comment by szxiangjn** [comment]
Hi,

Thanks for your interest in our work. We have realeased the code in `build_dataset` directory.
